export default {
	// ACTIONS
	AUTH_OPEN: 'AUTH_OPEN',
	AUTH_LOGIN: 'AUTH_LOGIN',
	AUTH_LOGOUT: 'AUTH_LOGOUT',
  SIGN_UP: 'SIGN_UP',


	// STATES
	AUTH_ANONYMOUS: 'AUTH_ANONYMOUS',
	AUTH_AWAITING_RESPONSE: 'AUTH_AWAITING_RESPONSE',
	AUTH_LOGGED_IN: 'AUTH_LOGGED_IN',
  AUTH_ERROR: 'AUTH_ERROR'
};
